"""Retrieval Agent models — Planner output and Ranker output schemas."""

from pydantic import Field

from .common import DeckForgeBaseModel
from .enums import Language, QueryPriority, SearchStrategy
from .state import RetrievedSource


class SearchQuery(DeckForgeBaseModel):
    """A single search query generated by the Retrieval Planner."""
    query: str
    strategy: SearchStrategy
    target_criterion: str | None = None
    language: Language
    priority: QueryPriority


class RetrievalSummary(DeckForgeBaseModel):
    """Summary statistics for the generated search queries."""
    total_queries: int
    by_strategy: dict[str, int] = Field(default_factory=dict)
    highest_priority_criteria: list[str] = Field(default_factory=list)


class RetrievalQueries(DeckForgeBaseModel):
    """Full output of the Retrieval Planner (Pass 1)."""
    search_queries: list[SearchQuery] = Field(default_factory=list)
    retrieval_summary: RetrievalSummary


class ExcludedDocument(DeckForgeBaseModel):
    """A document excluded by the Retrieval Ranker with reason."""
    doc_id: str
    reason: str


class RankedSourcesOutput(DeckForgeBaseModel):
    """Full output of the Retrieval Ranker (Pass 2)."""
    ranked_sources: list[RetrievedSource] = Field(default_factory=list)
    excluded_documents: list[ExcludedDocument] = Field(default_factory=list)
