"""Canonical template contract for blueprint generation and validation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

OwnershipType = Literal["house", "dynamic", "hybrid"]


@dataclass(frozen=True)
class TemplateSectionSpec:
    """One canonical template section specification."""

    section_id: str
    section_name: str
    slide_numbers: list[int]
    layout_families: list[str]
    ownership: OwnershipType
    required: bool
    repeatable: bool
    max_dynamic_slides: int | None


TEMPLATE_SECTION_ORDER: list[TemplateSectionSpec] = [
    TemplateSectionSpec(
        section_id="S01",
        section_name="Proposal Shell",
        slide_numbers=[1],
        layout_families=["Proposal Cover"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S02",
        section_name="Introduction Message",
        slide_numbers=[2],
        layout_families=["Introduction Message"],
        ownership="dynamic",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S03",
        section_name="Table of Contents",
        slide_numbers=[3],
        layout_families=["ToC / Agenda"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S04",
        section_name="Introduction and Understanding (Divider)",
        slide_numbers=[4],
        layout_families=["01"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S05",
        section_name="Understanding of Project (Content Block)",
        slide_numbers=[5, 6, 7, 8],
        layout_families=[
            "KSA",
            "Pillars of the Vision",
            "Vision Realization Programs Numbers",
            "Vision Realization Programs",
        ],
        ownership="dynamic",
        required=True,
        repeatable=False,
        max_dynamic_slides=4,
    ),
    TemplateSectionSpec(
        section_id="S06",
        section_name="Why Strategic Gears (Divider)",
        slide_numbers=[9],
        layout_families=["02"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S07",
        section_name="Why Strategic Gears (Evidence Content)",
        slide_numbers=[10],
        layout_families=["Services - Detailed Case"],
        ownership="dynamic",
        required=True,
        repeatable=False,
        max_dynamic_slides=3,
    ),
    TemplateSectionSpec(
        section_id="S08",
        section_name="Methodology (Divider)",
        slide_numbers=[11],
        layout_families=["03"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S09",
        section_name="Methodology (Content Block)",
        slide_numbers=[12, 13, 14],
        layout_families=[
            "Methodology -3- Overview of Phases",
            "Methodology -3- Focused Phase",
            "Methodology - Detailed Phase",
        ],
        ownership="dynamic",
        required=True,
        repeatable=False,
        max_dynamic_slides=3,
    ),
    TemplateSectionSpec(
        section_id="S10",
        section_name="Project Timeline and Outcome (Divider)",
        slide_numbers=[15],
        layout_families=["04"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S11",
        section_name="Project Timeline and Outcomes (Table Content)",
        slide_numbers=[16],
        layout_families=["Heading only (deliverables table)"],
        ownership="dynamic",
        required=True,
        repeatable=False,
        max_dynamic_slides=2,
    ),
    TemplateSectionSpec(
        section_id="S12",
        section_name="Proposed Project Team (Divider)",
        slide_numbers=[17],
        layout_families=["05"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S13",
        section_name="Project Governance (Divider)",
        slide_numbers=[18],
        layout_families=["06"],
        ownership="hybrid",
        required=True,
        repeatable=False,
        max_dynamic_slides=1,
    ),
    TemplateSectionSpec(
        section_id="S14",
        section_name="Corporate Main Shell Sequence",
        slide_numbers=[19, 20, 21, 22, 23],
        layout_families=["Main Cover", "Overview", "What Drives Us", "At a Glance", "Why Strategic Gears"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S15",
        section_name="Deep Experience Sequence",
        slide_numbers=[24, 25, 26, 27],
        layout_families=["Deep Experience 1/4", "Deep Experience 2/4", "Deep Experience 3/4", "Deep Experience 4/4"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S16",
        section_name="Corporate Capability Shell Sequence",
        slide_numbers=[28, 29, 30, 31, 32, 33],
        layout_families=[
            "A House of Expertise",
            "Vast Network",
            "Purpose Beyond Business 1/2",
            "Purpose Beyond Business 2/2",
            "Our Services",
            "Strategy",
        ],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S17",
        section_name="Organizational Excellence (Service Divider)",
        slide_numbers=[41],
        layout_families=["Organizational Excellence"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S18",
        section_name="Organizational Excellence Case Pool",
        slide_numbers=[42, 43, 44, 45, 46, 47, 48, 49, 50],
        layout_families=["Services - Cases"],
        ownership="house",
        required=False,
        repeatable=True,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S19",
        section_name="Marketing (Service Divider)",
        slide_numbers=[51],
        layout_families=["Marketing"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S20",
        section_name="Marketing Case Pool",
        slide_numbers=[52, 53, 54, 55, 56],
        layout_families=["Services - Cases"],
        ownership="house",
        required=False,
        repeatable=True,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S21",
        section_name="Digital, Cloud, and AI (Service Divider)",
        slide_numbers=[57],
        layout_families=["Digital, Cloud, and AI"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S22",
        section_name="Digital, Cloud, and AI Case Pool",
        slide_numbers=[58, 59, 60],
        layout_families=["Services - Cases"],
        ownership="house",
        required=False,
        repeatable=True,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S23",
        section_name="People Advisory (Service Divider)",
        slide_numbers=[61],
        layout_families=["People Advisory"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S24",
        section_name="People Advisory Case Pool",
        slide_numbers=[62, 63],
        layout_families=["Services - Cases"],
        ownership="house",
        required=False,
        repeatable=True,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S25",
        section_name="Deals Advisory (Service Divider)",
        slide_numbers=[64],
        layout_families=["Deals Advisory"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S26",
        section_name="Deals Advisory Case Pool",
        slide_numbers=[65, 66, 67],
        layout_families=["Services - Cases"],
        ownership="house",
        required=False,
        repeatable=True,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S27",
        section_name="Research (Service Divider)",
        slide_numbers=[68],
        layout_families=["Research"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S28",
        section_name="Research Case Pool",
        slide_numbers=[69],
        layout_families=["Services - Cases"],
        ownership="house",
        required=False,
        repeatable=True,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S29",
        section_name="Our Leadership (Divider)",
        slide_numbers=[70],
        layout_families=["Our Leadership"],
        ownership="house",
        required=False,
        repeatable=False,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S30",
        section_name="Leadership Bio Pool",
        slide_numbers=[71, 72, 73, 74, 75, 76, 77, 78, 79],
        layout_families=["two team members"],
        ownership="house",
        required=False,
        repeatable=True,
        max_dynamic_slides=None,
    ),
    TemplateSectionSpec(
        section_id="S31",
        section_name="Closing Shell Sequence",
        slide_numbers=[80, 81],
        layout_families=["Know More Page", "Contact"],
        ownership="house",
        required=True,
        repeatable=False,
        max_dynamic_slides=None,
    ),
]

